version: 2.1

jobs:
  build_amd64:
    docker:
      - image: cimg/base:current
    resource_class: large
    environment:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - checkout
      - run:
          name: Clone Foundry Repository
          command: git clone https://github.com/foundry-rs/foundry.git
      - run:
          name: Clone Foundry Images Repository
          command: git clone https://github.com/Dzejkop/foundry-images.git
      - setup_remote_docker
      - run:
          name: Build AMD64 Image
          command: |
            cd foundry
            docker buildx build \
              --platform linux/amd64 \
              --load \
              --single-platform \
              --file ../foundry-images/Dockerfile.debian \
              -t dzejkop/foundry:amd64 \
              .
      - run:
          name: Save AMD64 Image
          command: |
            docker save dzejkop/foundry:amd64 -o foundry_amd64.tar
      - persist_to_workspace:
          root: .
          paths:
            - foundry_amd64.tar

  build_arm64:
    docker:
      - image: cimg/base:current
    resource_class: arm.large
    environment:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - checkout
      - run:
          name: Clone Foundry Repository
          command: git clone https://github.com/foundry-rs/foundry.git
      - run:
          name: Clone Foundry Images Repository
          command: git clone https://github.com/Dzejkop/foundry-images.git
      - setup_remote_docker
      - run:
          name: Build ARM64 Image
          command: |
            cd foundry
            docker buildx build \
              --platform linux/arm64 \
              --load \
              --single-platform \
              --file ../foundry-images/Dockerfile.debian \
              -t dzejkop/foundry:arm64 \
              .
      - run:
          name: Save ARM64 Image
          command: |
            docker save dzejkop/foundry:arm64 -o foundry_arm64.tar
      - persist_to_workspace:
          root: .
          paths:
            - foundry_arm64.tar

  create_and_push_manifest:
    docker:
      - image: cimg/base:stable
    environment:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Load AMD64 Image
          command: docker load -i foundry_amd64.tar
      - run:
          name: Load ARM64 Image
          command: docker load -i foundry_arm64.tar
      - run:
          name: Log in to Docker Hub
          command: echo $DOCKER_PERSONAL_ACCESS_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Create and Push Multi-Arch Image
          command: |
            docker buildx imagetools create \
              --tag dzejkop/foundry:latest \
              dzejkop/foundry:arm64 dzejkop/foundry:amd64
            docker manifest push dzejkop/foundry:latest


workflows:
  build_and_push:
    jobs:
      - build_amd64
      - build_arm64
      - create_and_push_manifest:
          requires:
            - build_amd64
            - build_arm64
