version: 2.1

jobs:
  build_amd64:
    docker:
      - image: cimg/base:current
    resource_class: large
    steps:
      - run:
          name: Clone Foundry Repository
          command: git clone https://github.com/foundry-rs/foundry.git
      - run:
          name: Log in to Docker Hub
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PERSONAL_ACCESS_TOKEN
      - setup_remote_docker
      - run:
          name: Build and Push AMD64 Image
          command: |
            cd foundry
            docker buildx create --use
            docker buildx build \
              --platform linux/amd64 \
              --file ../Dockerfile.debian \
              -t dzejkop/foundry:amd64 \
              --push .

  build_arm64:
    docker:
      - image: cimg/base:current
    resource_class: arm.large
    steps:
      - run:
          name: Clone Foundry Repository
          command: git clone https://github.com/foundry-rs/foundry.git
      - run:
          name: Log in to Docker Hub
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PERSONAL_ACCESS_TOKEN
      - setup_remote_docker
      - run:
          name: Build and Push ARM64 Image
          command: |
            cd foundry
            docker buildx create --use
            docker buildx build \
              --platform linux/arm64 \
              --file ../Dockerfile.debian \
              -t dzejkop/foundry:arm64 \
              --push .

  create_and_push_manifest:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Log in to Docker Hub
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PERSONAL_ACCESS_TOKEN
      - setup_remote_docker
      - run:
          name: Create and Push Multi-Platform Manifest
          command: |
            docker manifest create dzejkop/foundry:latest \
              --amend dzejkop/foundry:amd64 \
              --amend dzejkop/foundry:arm64
            docker manifest push dzejkop/foundry:latest

workflows:
  build_and_push:
    jobs:
      - build_amd64
      - build_arm64
      - create_and_push_manifest:
          requires:
            - build_amd64
            - build_arm64

